let c = 2;
try {
  let a = 2 + b;

} catch(e) {

  console.log(e.message);
  //throw the new error;

}

console.log('test');
